name: Deploy Node.js App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Kalau ada build step, boleh tambah di sini
      # - name: Build project
      #   run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ftp.nasadef.com.my
          username: ${{ razif@nasadef.com.my }}
          password: ${{ Nikrazif@1 }}
          local-dir: ./        # folder repo awak
          server-dir: /Dating/ # folder di server
